# Generated by Django 5.2.4 on 2025-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0002_fooditem_category_alter_fooditem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(),
        ),
    ]
